INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (47708, 'Alfred Hitchcock Presents', 'English', 1955, 1962, 'Alfred J. Hitchcock Productions');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (52520, 'The Twilight Zone', null, 1959, 1964, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (53488, 'The Bugs Bunny Show', 'English', 1960, 1975, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (62550, 'The Bugs Bunny/Road Runner Hour', 'English', 1968, 1978, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (62588, 'Mister Rogers'' Neighborhood', 'English', 1968, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (63929, 'Monty Python''s Flying Circus', 'English', 1969, 1974, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (71075, 'The World at War', 'English', 1973, 1974, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (72500, 'Fawlty Towers', 'English', 1975, 1979, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (74006, 'I, Claudius', 'English', 1976, 1976, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (75537, 'Mind Your Language', 'English', 1977, 1986, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (80306, 'Yes Minister', 'English', 1980, 1984, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (81834, 'Das Boot', 'German', 1985, 1987, 'Bavaria Film');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (81846, 'Cosmos', null, 1980, 1980, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (81912, 'Only Fools and Horses....', 'English', 1981, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (83100, 'Priklyucheniya Sherloka Kholmsa i doktora Vatsona: Sobaka Baskerviley', 'Russian', 1981, 1981, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (86661, 'The Adventures of Sherlock Holmes', 'English', 1984, 1985, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (86831, 'Yes, Prime Minister', 'English', 1986, 1987, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (88484, 'Blackadder II', 'English', 1986, 1986, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (88509, 'Dragon Ball: Doragon bôru', null, 1986, 1989, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (90509, 'The Return of Sherlock Holmes', 'English', 1986, 1988, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (92324, 'Blackadder the Third', 'English', 1987, 1987, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (92337, 'Dekalog', 'Polish', 1989, 1990, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (92455, 'Star Trek: The Next Generation', 'English', 1987, 1994, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (94517, 'Mystery Science Theater 3000', 'English', 1988, 1999, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (94525, 'Poirot', 'English', 1989, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (96548, 'Blackadder Goes Forth', 'English', 1989, 1989, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (96639, 'Lonesome Dove', 'English', 1989, 1989, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (96657, 'Mr. Bean', 'English', 1990, 1995, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (96697, 'The Simpsons', 'Chinese', 1989, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (98769, 'The Civil War', 'English', 1990, 1990, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (98904, 'Seinfeld', 'English', 1989, 1998, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (98936, 'Twin Peaks', 'English', 1990, 1991, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (103359, 'Batman: The Animated Series', 'English', 1992, 1995, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (106028, 'Homicide: Life on the Street', 'English', 1993, 1999, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (106179, 'The X Files', 'English', 1993, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (108778, 'Friends', 'English', 1994, 2004, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (108855, 'The Memoirs of Sherlock Holmes', 'English', 1994, 1994, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (111893, 'The Beatles Anthology', 'English', 1995, 1996, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (111958, 'Father Ted', 'English', 1995, 1998, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (112130, 'Pride and Prejudice', 'English', 1995, 1995, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (112159, 'Shin seiki evangerion', 'English', 1995, 1996, 'Gainax');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (118266, 'The New Batman Adventures', 'English', 1997, 1999, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (118273, 'Brass Eye', 'English', 1997, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (118421, 'Oz', 'English', 1997, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (120570, 'From the Earth to the Moon', 'English', 1998, 1998, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (121220, 'Dragon Ball Z: Doragon bôru zetto', null, 1989, 1996, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (121955, 'South Park', 'English', 1997, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (129690, 'I''m Alan Partridge', 'English', 1997, 2002, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (141842, 'The Sopranos', 'English', 1999, 2007, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (158417, 'Mahabharat', 'Hindi', 1988, 1990, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (163507, 'Whose Line Is It Anyway?', 'English', 1998, 2007, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (185906, 'Band of Brothers', 'English', 2001, 2001, 'DreamWorks');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (187664, 'Spaced', 'English', 1999, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (193676, 'Freaks and Geeks', 'English', 1999, 2000, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (200276, 'The West Wing', 'English', 1999, 2006, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (203082, 'Rurouni Kenshin: Meiji Kenkaku Romantan: Tsuioku Hen', 'Japanese', 1999, 1999, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (213338, 'Kaubôi bibappu', 'Japanese', 1998, 1999, 'Bandai Visual Company');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (214341, 'Dragon Ball Z', 'English', 1996, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (229889, 'El Chavo del Ocho', 'Spanish', 1972, 1983, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (237123, 'Coupling', 'English', 2000, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (248654, 'Six Feet Under', 'English', 2001, 2005, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (262150, 'Black Books', 'English', 2000, 2004, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (264235, 'Curb Your Enthusiasm', 'English', 2000, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (264700, 'Ikinci Bahar', 'Turkish', 1998, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (268093, 'Ramayan', 'Hindi', 1987, 1988, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (275137, 'Justice League', 'English', 2001, 2004, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (280249, 'Dragon Ball', 'English', 1995, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (281491, 'Still Game', 'English', 2002, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (286486, 'The Shield', 'English', 2002, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (290978, 'The Office', 'English', 2001, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (296310, 'The Blue Planet', 'English', 2001, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (303461, 'Firefly', 'English', 2002, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (306414, 'The Wire', 'English', 2002, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (314979, 'Battlestar Galactica', 'English', 2003, 2003, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (315008, 'GTO', 'Japanese', 1999, 2000, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (318871, 'Kenpû Denki Berserk', 'English', 1997, 1998, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (348914, 'Deadwood', 'English', 2004, 2006, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (353049, 'Chappelle''s Show', 'English', 2003, 2006, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (367279, 'Arrested Development', 'English', 2003, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (380136, 'QI', 'English', 2003, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (384766, 'Rome', 'English', 2005, 2007, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (386676, 'The Office', 'English', 2005, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (387764, 'Peep Show', 'English', 2003, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (388629, 'One Piece: Wan pîsu', 'Japanese', 1999, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (403778, 'Long Way Round', 'English', 2004, 2010, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (407362, 'Battlestar Galactica', 'English', 2004, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (412142, 'House M.D.', 'English', 2004, 2012, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (417299, 'Avatar: The Last Airbender', 'English', 2005, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (417349, 'North & South', 'English', 2004, 2004, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (417373, 'The Venture Bros.', 'English', 2003, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (421357, 'Hagane no renkinjutsushi', 'Japanese', 2003, 2004, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (423731, 'Samurai chanpurû', 'Japanese', 2004, 2005, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (426719, 'Hunter x Hunter', 'Japanese', 1999, 2001, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (434706, 'Monster', 'English', 2004, 2010, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (436992, 'Doctor Who', 'English', 2005, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (459159, 'The Thick of It', 'English', 2005, 2012, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (472027, 'John Adams', 'English', 2008, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (472954, 'It''s Always Sunny in Philadelphia', 'English', 2005, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (475784, 'Westworld', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (481256, 'Hajime no ippo', 'Japanese', 2000, 2002, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (487831, 'The IT Crowd', 'English', 2006, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (758745, 'Friday Night Lights', 'English', 2006, 2011, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (773262, 'Dexter', 'English', 2006, 2021, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (795176, 'Planet Earth', 'English', 2006, 2006, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (804503, 'Mad Men', 'English', 2007, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (863046, 'Flight of the Conchords', 'English', 2007, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (877057, 'Death Note: Desu nôto', 'Japanese', 2006, 2007, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (903747, 'Breaking Bad', 'English', 2008, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (944947, 'Game of Thrones', 'English', 2011, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (979432, 'Boardwalk Empire', 'English', 2010, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (988818, 'Gintama', 'Japanese', 2005, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (988824, 'Naruto: Shippûden', 'English', 2007, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (994314, 'Kôdo giasu - Hangyaku no rurûshu: Code Geass - Lelouch of the Rebellion', 'Japanese', 2006, 2012, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (995832, 'Generation Kill', 'English', 2008, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1043822, 'Vratice se rode', 'Serbian', 2007, 2008, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1051155, 'The Universe', 'English', 2007, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1124373, 'Sons of Anarchy', 'English', 2008, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1190634, 'The Boys', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1266020, 'Parks and Recreation', 'English', 2009, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1298820, 'Clannad: After Story', 'Japanese', 2008, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1305826, 'Adventure Time', 'Spanish', 2010, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1355642, 'Hagane no renkinjutsushi', 'Japanese', 2009, 2012, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1442449, 'Spartacus: Blood and Sand', 'English', 2010, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1475582, 'Sherlock', 'English', 2010, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1486217, 'Archer', 'English', 2009, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1489428, 'Justified', 'English', 2010, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1492966, 'Louie', 'English', 2010, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1494191, 'The Untold History of the United States', 'English', 2012, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1508238, 'Apocalypse: La 2ème guerre mondiale', 'French', 2009, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1513168, 'Through the Wormhole', 'English', 2010, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1518542, 'Sarabhai V/S Sarabhai', 'Hindi', 2004, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1533395, 'Life', 'English', 2009, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1534360, 'Ezel', 'Turkish', 2009, 2011, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1606375, 'Downton Abbey', 'English', 2010, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1628033, 'Top Gear', 'English', 2002, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1641384, 'Young Justice', 'English', 2010, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1733785, 'Bron/Broen', 'Swedish', 2011, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1758429, 'Spartacus: Gods of the Arena', 'English', 2011, 2011, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1795096, 'Behzat Ç.: Bir Ankara Polisiyesi', 'Turkish', 2010, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1806234, 'Human Planet', 'English', 2011, 2011, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1831164, 'Leyla ile Mecnun', 'Turkish', 2011, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1832668, 'How the Universe Works', 'English', 2010, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1856010, 'House of Cards', 'English', 2013, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1865718, 'Gravity Falls', 'Spanish', 2012, 2016, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1870479, 'The Newsroom', 'English', 2012, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1877368, 'The Great British Bake Off', 'English', 2010, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1877514, 'The Vietnam War', 'English', 2017, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (1910272, 'Steins Gate', 'Japanese', 2011, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2049116, 'Gomorra: La serie', 'Italian', 2014, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2069688, 'World War II in Colour', 'English', 2009, 2009, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2085059, 'Black Mirror', 'English', 2011, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2092588, 'Frozen Planet', 'English', 2011, 2012, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2098220, 'Hunter x Hunter', 'Japanese', 2011, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2100976, 'Impractical Jokers', 'English', 2011, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2243973, 'Hannibal', 'English', 2013, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2244495, 'The Eric Andre Show', 'English', 2012, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2297757, 'Nathan for You', 'English', 2013, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2303687, 'Line of Duty', 'English', 2012, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2356777, 'True Detective', 'English', 2014, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2395695, 'Cosmos: A Spacetime Odyssey', 'English', 2014, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2401256, 'The Night Of', 'English', 2016, 2016, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2433738, 'Wentworth', 'English', 2013, 2021, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2442560, 'Peaky Blinders', 'Italian', 2013, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2560140, 'Shingeki no kyojin', 'Japanese', 2013, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2571774, 'Africa', 'English', 2013, 2013, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2575988, 'Silicon Valley', 'English', 2014, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2701582, 'Endeavour', 'English', 2012, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2707408, 'Narcos', 'English', 2015, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2802850, 'Fargo', 'English', 2014, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (2861424, 'Rick and Morty', 'English', 2013, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3032476, 'Better Call Saul', 'English', 2015, 2021, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3230854, 'The Expanse', 'English', 2015, null, 'Alcon Entertainment');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3322312, 'Daredevil', 'English', 2015, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3398228, 'BoJack Horseman', 'English', 2014, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3398540, 'Haikyuu!!', 'English', 2014, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3530232, 'Last Week Tonight with John Oliver', 'English', 2014, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3718778, 'Over the Garden Wall', 'English', 2014, 2014, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3895150, 'Shigatsu wa kimi no uso', 'Japanese', 2014, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (3920596, 'Big Little Lies', 'English', 2017, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4063800, 'Le Bureau des Légendes', 'French', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4082744, 'Detectorists', 'English', 2014, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4093826, 'Twin Peaks', 'English', 2017, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4158110, 'Mr. Robot', 'English', 2015, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4236770, 'Yellowstone', 'English', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4269716, 'Umbre', 'Romanian', 2014, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4288182, 'Atlanta', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4295140, 'Chef''s Table', 'English', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4299972, 'The Jinx: The Life and Deaths of Robert Durst', 'English', 2015, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4508902, 'One Punch Man: Wanpanman', 'Japanese', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4574334, 'Stranger Things', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4647692, 'Letterkenny', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4742876, 'TVF Pitchers', 'Hindi', 2015, 2015, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4786824, 'The Crown', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4834232, 'Critical Role', 'English', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (4934214, 'Taskmaster', 'English', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5099020, 'Aranyélet', 'Hungarian', 2015, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5189670, 'Making a Murderer', 'English', 2015, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5249462, 'Boku dake ga inai machi', 'Japanese', 2016, 2016, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5288312, 'Skam', 'Norwegian', 2015, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5290382, 'Mindhunter', 'English', 2017, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5421602, 'Anne', 'English', 2017, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5425186, 'Horace and Pete', 'English', 2016, 2016, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5491994, 'Planet Earth II', 'French', 2016, 2016, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5555260, 'This Is Us', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5687612, 'Fleabag', 'English', 2016, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5712554, 'The Grand Tour', 'English', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5753856, 'Dark', 'German', 2017, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5788792, 'The Marvelous Mrs. Maisel', 'English', 2017, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (5897304, 'Mob Psycho 100', 'Japanese', 2016, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6025022, 'Justice League Unlimited', 'English', 2004, 2006, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6077448, 'Sacred Games', 'Hindi', 2018, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6108262, 'Senke nad Balkanom', 'Serbian', 2017, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6111552, 'Content Cop', 'English', 2015, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6763664, 'The Haunting of Hill House', 'English', 2018, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6769208, 'Blue Planet II', 'English', 2017, 2017, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (6958022, 'The Defiant Ones', 'English', 2017, 2017, 'Alcon Entertainment');
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7137906, 'When They See Us', 'English', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7221388, 'Cobra Kai', 'English', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7278862, 'L''amica geniale', 'Italian', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7366338, 'Chernobyl', 'English', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7562112, 'Pose', 'English', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7651892, 'One Strange Rock', 'English', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7660850, 'Succession', 'English', 2018, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7908628, 'What We Do in the Shadows', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (7920978, 'Sahsiyet', 'Turkish', 2018, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (8111088, 'The Mandalorian', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (8289930, 'Formula 1: Drive to Survive', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (8420184, 'The Last Dance', 'English', 2020, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (8595766, 'Yeh Meri Family', 'Hindi', 2018, 2018, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (8788458, 'Yakusoku no Neverland', 'Japanese', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9103932, 'Greatest Events of WWII in Colour', 'English', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9140342, 'It''s a Sin', 'English', 2021, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9253866, 'Our Planet', 'English', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9335498, 'Demon Slayer: Kimetsu No Yaiba', 'Japanese', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9398466, 'Delhi Crime', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9432978, 'Kota Factory', 'Hindi', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9561862, 'Love, Death & Robots', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (9566030, 'Pew News', 'English', 2018, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10048342, 'The Queen''s Gambit', 'English', 2020, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10233448, 'Vinland Saga', 'Japanese', 2019, 2019, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10332508, 'Primal', 'English', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10530900, 'Gullak', 'Hindi', 2019, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10850932, 'Sa-rang-eui bul-sa-chak', 'Korean', 2019, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (10986410, 'Ted Lasso', 'English', 2020, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (11301642, 'Bir Baskadir', 'Turkish', 2020, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (12004706, 'Panchayat', 'Hindi', 2020, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (12343534, 'Jujutsu Kaisen', 'Japanese', 2020, null, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (12392504, 'Scam 1992: The Harshad Mehta Story', 'Hindi', 2020, 2020, null);
INSERT INTO `movie-master`.TV_Series (ID, Title, Lang, Start_Year, End_Year, Production_House_Name) VALUES (12451520, 'Saikojiman Gwaenchanha', 'Korean', 2020, 2020, null);
;
