INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('2.4.7. Films', '9@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('2D Entertainment', 'e0u2qu6zwtv8u6@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('40 Acres & A Mule Filmworks', 'pak47r@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('A.G. Films', '2gf@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Aamir Khan Productions', '0k9260j5zsqb5zjckw6d@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Aashirvad Cinemas', 'p2w6cxqiz9iov7@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('AB Svensk Filmindustri', '4s3ovc581dlky4s1@charter.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('ABC Animation', 'o7l@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Act III Communications', 'jwf74nopjwmndfbwir@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Akira Committee Company Ltd.', '0y3h@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Alcon Entertainment', '08@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Alfred J. Hitchcock Productions', 'fqilz8uff2l447i@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Allfilm', '1g96xcbo2hvyoa@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Altavista Films', '7@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('American Zoetrope', 'c3r6i0n9j3@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('AMLF', '1grk@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Amuse', '48hyhe339an@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Amuse Soft', 'g@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Animal Kingdom', '3o7cvueas@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Anjum Rizvi Film Company', '29j7f27sujxblvs@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Annapurna Pictures', 'hn7@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Anurag Kashyap Films', 'v0@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('APJAC Productions', 'aigc0t6f0gbtr3k@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Applause Bhansali Productions', 'oe1b0tojchft4i@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Arka Mediaworks', 'zv52y5@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Armada Productions', '725ag7l@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Artcam International', 'o1jjdwjf21mohk7tait7@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Artisan Entertainment', '4fcg5ablih6iqkuos63q@charter.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Asghar Farhadi Productions', 'fj3vlsfra30ezofo@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ashton Productions', 'ibszh1e@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ashutosh Gowariker Productions', 'ga1vgzolg1qgmnotyirk@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Asymmetrical Productions', '3kxv54zsc187z3lgd@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Atresmedia Cine', '55v44jsi@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Audiovisual Development Bureau, Ministerio da Cultura', 'p5hrc@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Avon Productions (II)', 'htviupuarq@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Avsar Film', 'b7nz62naetcn@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Backup Media', '7ihhti0hsx4n@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Bandai Visual Company', 'jpfr@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Barcino Films', 'kd3kmzwgqm6f9wwv2@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Barunson E&A', 'enklr@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Bavaria Film', 'hcl6upfdezh@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Be Gentlemen Limited Partnership', '8xo006u8o9ooa1g4@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Belarusfilm', 'hk9p1dicqruy7pvn5c@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Besiktas Kültür Merkezi (BKM)', 'ffl3s8998dhuc8kc@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Black Bear Pictures', '8o@charter.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Block 2 Pictures', 'qbkgthkl1@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Blueprint Pictures', 'riaj1fvmamj@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Bold Films', '1@charter.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Boundscript', 'didtt39a3@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Brandywine Productions', '2ei@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('British Film Institute (BFI)', '84g9rkpy7arpfn@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Brooksfilms', 't2o6bfo4py74xf4us5@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Bryna Productions', '43kazd9r14rw@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('BSB', '193ps3mj72h@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Buena Vista Home Entertainment', '80khmgtujkamh93a94@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Buena Vista International Film Production (Germany)', 'pszxhoifpd03gel@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Bulb Chamka', 'y@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Buster Keaton Productions', 'ibra9m9d35jf@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Campanile Productions', 'am5x@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Canal+', 'pyf0sfk0z9qtwux83@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cape of Good Films', 'zf7tm@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Carolco Pictures', '9l6r7ggkowwwaciwbp8@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Castle Rock Entertainment', 'qj6moo5l3@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cecchi Gori Pictures', 'gvkejhfsqv@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Celador Films', '2sp47tkckte@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Channel Four Films', 'hdatk707xjaw9@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Charles Chaplin Productions', 'yd7g@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Charles K. Feldman Group', '67fhcquk23a@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Chartoff-Winkler Productions', 'uup1@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Chernin Entertainment', 'berhny0neetz4@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Chrome Pictures', 'p8zumbwce@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('CiBy 2000', 'w6ho9lhe2j136r2p3@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cinema ''84', 'r@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cinematograph AB', '80jlbm0kjqsl0@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cineriz', 'cds4@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('CJ Entertainment', 'mponmjboujz0wnz9@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Claudie Ossard Productions', 'l7@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Colour Yellow Productions', 'ngjpa8iajnvfdacm@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Columbia Pictures', '399v60tyokfwb3@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Compagnie Industrielle et Commerciale Cinématographique (CICC)', 'ogigkbtu@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Constantin Film', 'njfw53ntntbiy36g@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Creavidi', '0dh9c@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Cristaldifilm', '9atdxwx2@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Daiei', 'wpzg8y1av2@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Danmarks Radio (DR)', 'k@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Decla-Bioscop AG', 'l4l0qppmnl9kee@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('DENTSU Music And Entertainment', 'oznumxrxszeut4n12@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dharma Productions', 'prb@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dijital Sanatlar Production', 'g01fswldn@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dimension Films', '4hccea7etj45gky@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dino de Laurentiis Cinematografica', 't1b12k8vg7i1x8y8s6nt@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dreamlab', 'odjtobmjz@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('DreamWorks', '40acvj7w3zh@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('DreamWorks Animation', 'c1l1d5tw1xy5iscum@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Dreamworks Pictures', 'st2hs4yl12ucm86fc5@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ealing Studios', 'ns399ubf2gd3v3@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Edward Small Productions', 'f0yiz2djm1@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Egg Films', 'eqsw91f634lgvq@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Element Pictures', 'ae2dbdg79@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('EMI Films', 'w3rn1atyry@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('ERA International', 'k394wd@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Eros International', 'iz7olyuc@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Estudios Picasso', 'b@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Excel Entertainment', 'iveqvirmnh@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Exclusive Media Group', 'kjg3jfx94z@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Fantasy Films', 'par942f8ylpitzls@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Filmco International Productions', 'w8r67bpew@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Filmsonor', '0u3mjoz97os3b@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Focus Features', 'pf50wqbuqo2t9@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('FortyFour Studios', 'rl47@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Forum Sarajevo', 'na90ertfte91edittx@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Fox 2000 Pictures', '8g2vz1@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Fox Film Corporation', 'ktr4nfhyyktpc@frontier.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Fox Searchlight Pictures', '2d7caxheoqdc2vbejmez@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Fox STAR Studios', '7e@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Friday Filmworks', 'hyvp@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Gainax', 'gx5xayrn@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Gaumont', 'j0hqw@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ghoulardi Film Company', '23o1n4kpbgse1qt2vk@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Globo Filmes', 'kivr57euj@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Goldcrest Films International', 'ykcauic94@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Golden Harvest Company', '68n3e2jgyxlzs9bovzj@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Grazing Goat Pictures', '2r0tm1i22c3@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Greenwich Film Productions', 'w8hdvqdvagyiny@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Gruskoff/Venture Films', '9u4yejjrxx241dh1@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('HandMade Films', 'c4skgyquyfine@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Harris-Kubrick Productions', 'xicmfybzf2vypl@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Hell''s Kitchen Films', '17@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Hemdale', 'guuoy06c5b35d6@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Hollywood Pictures', '8cdq6w3pm7vxxh@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Hombale Films', 'teguxxduk6wvon66wr@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Horizon Pictures', 'dxs8r4cey3ls2mqq@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Horizon Pictures (II)', '8dr782ldzoyvzv@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Icon Entertainment International', 'puvz4lqj8d5@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Igor Film', 'bvd31@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('International Film Investors', 'ch28db5a@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Jack Rollins & Charles H. Joffe Productions', 'axl@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Jalem Productions', 'ytm@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Jar Pictures', 'z@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Jet Tone Production', 'g@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('John Ford Productions', '9dnyvp0le@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Jolly Film', 'mo9xclvkw7c@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Junglee Pictures', 'lr496mefr5ss9zk@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Kang Je-Kyu Film Co. Ltd.', 'qkw77ogf66j9@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Kanun parvaresh fekri', '9nw9fpsx626h3kkw5@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Kim Ki-Duk Film', 'sob1rughve8xl0g02@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Kôdansha', '5y14jfwkp87f2b5@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Korea Pictures', 'uoi5x7@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Kurosawa Production Co.', '0jstwc7eo2q7mqc8t74x@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Lawrence Truman Productions', 'jsv5ho@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Les Films Corona', '5t4d5m0cysoz4cf1@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Les Films de la Pléiade', 'i9e@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Les Films du Carrosse', 'oa5k5dh29z0aq@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Les Films Séville', 'bsbwcxionaxmpkjtq@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Liberty Films (II)', 'rri6@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Lilies Films', '2qth2ahyl6x@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Lionsgate', 'yi@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Live Entertainment', 'tczq7@gmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('London Film Productions', 'l0mnn0@frontier.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Lucasfilm', 'hga3q675uf1zfxees@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Mars Film', 'a6uz8f8d@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Marvel Studios', 'gxa5x@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Matchbox Pictures', '7bdalpq4ld@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Matten Productions', 'kcqis58kx1@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Media Asia Films', '090yjrw91dqm6era@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Melampo Cinematografica', '69xsng96ctknkpmah3wf@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Melodrama Pictures', 'vi27ygma0zm75e8k@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Metro-Goldwyn-Mayer (MGM)', 'fg0@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('micro_scope', 'e@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Miramax', '2r@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('MK2 Productions', 'elmwn1fm25k@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Mooz Films', '7kx0xi@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Mosfilm', 'jzjxazf6p8ohbzf1dwh@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Natant', 'z8gixz72dpjp0k71e@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('NBC Film', 'jhihcw0472c9di42ohue@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Nero-Film AG', 'tchh430dyntc@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('New Line Cinema', '8hg2miv2u0k949xsc@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('New Regency Productions', 'wydnrg3@frontier.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Newmarket Capital Group', '4rw1r@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('NH Studioz', 'b15qu08six2a2rqr7lt@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Nibariki', 'bsl@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Nimbus Film Productions', 'psyk6np0t9r@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Nippon Television Network (NTV)', '6gr6gx0bj8d7yjosa0wo@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Norma Productions', 'h86sw1@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Nouvelles Éditions de Films (NEF)', 'vv70l56@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('O2 Filmes', 'nlm@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('O3 Turkey Medya', 'v2fulcfacqkaj6x@gmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Orion-Nova Productions', 'qku2vsprqu5xuyjnq@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Otto Preminger Films', 'u79k6i5hl9vp9g3@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Pakula-Mulligan', 'skp7fnoqnbz2tyy87c@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Palomar Pictures International', 'lgcjss5hmgosh@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Pandora Cinema', 'lchwucbocb@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Panorama Studios', 'rddygqx79norp12m78l@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Paramount Pictures', 'ur@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Paramount Vantage', 'h2zebvsx@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Participant', 'enyt0ojrrcpbxx@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Pathé', '23n9w1x94alq@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Pathé Consortium Cinéma', 'n4pq1@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Paul Gregory Productions', 'kbf8@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Peregrine', 'klmvyennf7rqbw8@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Personafilm', 'g@gmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Pixar Animation Studios', '2inopuved84nm5he@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('PolyGram Filmed Entertainment', 'afzian0h5d6wm07@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ponti-De Laurentiis Cinematografica', 'b@charter.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Produzioni De Sica (PDS)', '2hzw5wzx8q@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Produzioni Europee Associate (PEA)', 'ryyqppd65t9z98ae3@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Python (Monty) Pictures', 'isyn2k3hn8xgrxt2p@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Quad Productions', '8pkp83av32m7zw@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('R.P. Productions', 'ev@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rafran Cinematografica', '8cnasrfvdskl@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rajkumar Hirani Films', '9arskaw077@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rakeysh Omprakash Mehra Pictures', 'pre2@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Réalisation d''art cinématographique (RAC)', 'exuq47z@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Red Granite Pictures', '44212t36u1gfi@verizon.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Ren Film', 'f58cpfygu@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rex Entertainment', 'wcs711kdeps9500m@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Riama Film', 'tn0q1kpsqdemj@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('RKO Radio Pictures', 'tgt9qw@comcast.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Road Movies Filmproduktion', 'sod53i2ax64k07@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Robert Wise Productions', 'tyref4l@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Romaine Film Corporation', 'b9b51u9jdl3cu1@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('ROMP', '945qm7@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rossen Films', 'cz8@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Roxlom Films Inc.', 'c6jn65z730kn1ui0@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Rupam Chitra', 'zdunisn@charter.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Santana Pictures Corporation', 'qxdgqx8jfydcqnc2osg@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Sciarlò', 'y0mbkmtg8n@verizon.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('See-Saw Films', '8gpljlnhsscncidvxmf@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Selznick International Pictures', '9@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Shamley Productions', 'h1s9uwvhk5gh4ehnjsy@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Shin Cine Communications', 'd@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Shinchosha Company', 'yg331ki@charter.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Shochiku', 'jjp3w1n@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Société générale des films', 'p64kble7wwmj352exou@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Sogepaq', 's8e6iw6xai3jbrhw1v8i@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Sony Pictures Classics', 'j1036aftp0iy0sw5@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Sony Pictures Entertainment (SPE)', 'cq0hes425xrh97y3eii@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Stage 6 Films', 'jkv7x5d4hq37xwpo5@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Stanley Kramer Productions', 'qer1shpfwjcvssk4ypj@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Strong Heart/Demme Production', 'cz91@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Studio Ghibli', '54emx@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Summit Entertainment', 'djrccx@outlook.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Svensk Filmindustri (SF)', '95001a07fo2u2l73sw@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('T-Series', 'm5@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Archers', 'gps9qflh3dvpj1h0lgll@outlook.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Associates & Aldrich Company', '2jgxo4rb@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Directors Company', '806hm@yahoo.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Ladd Company', '64rx4ib98l7qd0rsjoj@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Mirisch Company', '4ny66wexl5y@comcast.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Mirisch Corporation', '9eu3u@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Mirisch Production Company', '4pb8ic@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The SPA Studios', 'e4413gosjrvn@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Walt Disney Company', 'e0aqowdx@verizon.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('The Weinstein Company', 'i9pcfvt40aj6dfv8@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Think Music', 'jsjhi7x9g@yahoo.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Tig Productions', 'p4b98qt0c9yce@hotmail.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Toho Company', 'xdm0zndjm00mu6q@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Tokuma Japan Communications', 'f@hotmail.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Tokuma Shoten', '89@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Tomson Films', 'csbtyhno@charter.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Tornasol Films', '7vruertur@frontier.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Touchstone Pictures', 'xd3wlkrxd892@gmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Truth Entertainment (II)', 'lxxgm@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Twentieth Century Fox', '7dwdypfjj7j8c@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('United Artists', 'y81vdg3@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Universal International Pictures (UI)', 'kdmz3rrb@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Universal Pictures', 'ao6fyq6kixs@hotmail.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Universum Film (UFA)', 'a68w82q422@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('UTV Motion Pictures', 'cyzfurhmflnszmcir@charter.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('UTV Spotboy', '0h6deoq47@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Viacom18 Motion Pictures', 'd0cm5@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Vinay Pictures', 'gekgbf@outlook.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Vinod Chopra Productions', 't14c7y7jr27@charter.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Walt Disney Pictures', 'wcqw4hnwr5psbgtxwtq@frontier.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Warner Bros.', 'hcgu1h@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Warner Independent Pictures (WIP)', 'dcjy@comcast.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Werner Herzog Filmproduktion', 'n25qzxxv@outlook.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Wiedemann & Berg Filmproduktion', 'mxhpezca6sa6sg2@verizon.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('William Castle Productions', 'rj0@comcast.net');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Yash Raj Films', 'mzo34f5xdc6geih@yahoo.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Yash Raj Films International Ltd.', 'zz@frontier.org');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Zanuck/Brown Productions', 'p6nnseh8fg3@yahoo.com');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Zazen Produções', 'naouvy2jf7@hotmail.gov');
INSERT INTO `movie-master`.Production_House (Name, Email) VALUES ('Zentropa Entertainments', 'wdit1x@charter.org');;