INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('a_southern_knight', 'a4@frontier.com', 0x46, 'Joseph Mann', 46);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('ackstasis', 'f9m@verizon.gov', 0x4D, 'Aaron Everett', 49);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('adamloeber-06950', 'iexrses183fmk@gmail.gov', 0x4D, 'Desiree Roberson', 31);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('aislingkellygonzalez', 'd5mvczm116c6nfuin6y@hotmail.net', 0x4D, 'Zachary Thornton', 41);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('anassaleh-56714', 's1d@outlook.com', 0x4D, 'Tracy Evans', 36);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('auuwws', 'fez3582@comcast.gov', 0x46, 'Steven Armstrong', 45);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('bencoops', 'b1f6q@comcast.net', 0x4D, 'Kimberly Campbell', 48);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('bob the moo', 'iu@verizon.org', 0x46, 'Peter Gordon', 25);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('ccthemovieman-1', 'zq45stea@frontier.net', 0x46, 'Christina Henderson', 25);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('cindel-2', 'bv8ukuzvqr92jy8enb@comcast.gov', 0x4D, 'Kenneth Ross', 47);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('CineMuseFilms', 'jcnapy2y79i11mo8@yahoo.net', 0x46, 'Antonio Wyatt', 49);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('clovenier-927-957545', '1@gmail.net', 0x46, 'Kristi Fitzgerald', 35);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('copperccso', 'w@frontier.com', 0x46, 'Lisa Rodriguez', 27);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('costounet2-1', '7tiqm7ink2nq@frontier.gov', 0x46, 'Jennifer Morrison', 41);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('D_Burke', 'ryjuho920m45itn@comcast.gov', 0x46, 'Dalton Alvarado', 20);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Dolf', 'plm5ea4wky5rtngk0@outlook.net', 0x4D, 'Kerry Warner', 38);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('driffma', '9a@hotmail.com', 0x4D, 'Jason Olson', 42);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('droog-56936', '29kca0qypqsf1v7@charter.org', 0x46, 'Tamara Salas', 46);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('ElJimbooo', 'dn@yahoo.com', 0x4D, 'Henry Bird', 28);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('elpresidente-4', 'gp@comcast.com', 0x46, 'Stephen Sutton', 25);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('evolvingh', 'yosdh1f7uulw9l9@yahoo.gov', 0x46, 'Lisa Martin', 38);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('fearfulofspiders', 'j4oql40te@hotmail.org', 0x4D, 'Timothy Paul', 32);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('FlikJedi719', 'aq1gc7kqzbvujq@comcast.com', 0x46, 'Michael Nguyen', 42);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('glammy', 'u3@hotmail.com', 0x46, 'Lisa Duncan', 27);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('haildevilman', 'd4gvdc69@frontier.net', 0x4D, 'Tara Perry', 30);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('harrybhangu', '97l5e1yq1n9ecf2cpf@gmail.com', 0x4D, 'Russell Williams', 25);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('henriquelrf', 'yu@verizon.com', 0x46, 'Destiny Owens', 21);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('htethtetsuhlaing', '255ooio0ho@outlook.net', 0x46, 'Barry Horton', 44);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('jdberkley', '04j1@comcast.gov', 0x46, 'Chad Davis', 26);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Jeremy_Urquhart', 'brc5qc1@frontier.com', 0x4D, 'James Long', 23);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('jlacerra', 'ubz8qt@frontier.gov', 0x46, 'David Casey', 35);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('joecoby45', 'w2gp009@comcast.gov', 0x4D, 'Alan Sanchez', 46);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Joeyistheman', 'uw2@comcast.org', 0x46, 'Donna Gonzalez', 47);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('konradbuczak', 'mpwt5d51zy@outlook.net', 0x46, 'Margaret Murphy', 39);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('kraley', 'u0mk@verizon.gov', 0x4D, 'Mrs. Melissa Acevedo', 29);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Lady_Targaryen', 'pqw7c@frontier.org', 0x4D, 'Brian Bray', 29);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('LJGull', '08qfxyit46rb@verizon.net', 0x4D, 'Blake West', 30);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('lmayer2', '5s2e7jz5387@yahoo.gov', 0x4D, 'Edward Warner', 33);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('luiscarvalho', '4z5h@charter.com', 0x4D, 'Michele Wood', 35);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('MadReviewer', 'kz7nca@yahoo.gov', 0x46, 'Dr. Andrew Gonzales', 48);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('marianstelian', 'nr6pk@yahoo.com', 0x4D, 'Jesse Coleman', 39);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Marwan-Bob', 'ncudn2h8laht1s6@verizon.net', 0x4D, 'Steven Rodriguez', 21);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('misha-wilkin', 'gi0n9qforjaed@gmail.com', 0x46, 'Sarah Sampson', 38);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('mjsjsmith', 'a9cbsfr22he26fudci9r@hotmail.net', 0x46, 'Jack Grant', 42);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Movie-12', 'zvw128c@verizon.com', 0x4D, 'Jimmy Crawford', 41);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('MovieAddict2016', '1p34rh3xzo0a8ma7f4k@gmail.org', 0x4D, 'Kevin Lopez', 21);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Mr_PCM', 's@gmail.com', 0x46, 'Leslie King', 26);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('mstomaso', 'ud4kv@hotmail.gov', 0x46, 'Tony Miller', 36);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('mysticfall', 'oh9zx8t0woy2eiu@comcast.org', 0x4D, 'Ashley Sandoval', 29);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('nathanmanson', 't@gmail.gov', 0x4D, 'Carrie Smith', 21);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('nixterboy', 'vlwnv9a15vm8r@yahoo.gov', 0x46, 'Ms. Sarah Eaton', 32);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('petermail', 'xnvd7ncl@verizon.org', 0x4D, 'Matthew Mitchell', 33);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Prestige_Never_Pride', '3y1rivr7y505vba@hotmail.com', 0x46, 'Mariah Martinez', 38);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('ravenclaw_girlrules', '4l4q2l8kz@verizon.com', 0x46, 'Paula Mcguire', 25);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('RichardRowell328', 'ssj9p228tdldjm7d4z@charter.com', 0x46, 'Shannon Roy', 39);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('rightwingisevil', '1qhnk@gmail.com', 0x46, 'Kaitlyn Davis', 47);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('sanjay219', 'v6d3vndnkpbw68deh08@charter.net', 0x4D, 'Michael Lee', 49);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('schnad', 'qm3@charter.gov', 0x46, 'Daniel Martinez', 27);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('SdrolionGM', 'ymt@gmail.gov', 0x4D, 'Mr. Nicholas White', 41);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('straightblaster', '6r8d43tkqrviv7y@charter.com', 0x4D, 'Dr. George Lee', 39);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('supah79', 'ogsdvt94@hotmail.org', 0x4D, 'Angela Goodman', 41);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('thecarmenlips', '5mqfhmrj3ut8uxwmko@outlook.gov', 0x46, 'Lisa Brown', 44);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('Thelightbulb', 'n2vxknzm671lnsx@frontier.gov', 0x46, 'Leslie Williams', 27);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('TheLittleSongbird', 'afc1pdtwajajefj3qc9l@gmail.gov', 0x46, 'Angelica Holloway', 27);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('thomaseb', 'v@charter.com', 0x46, 'Paul Hudson', 50);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('TxMike', 'm@yahoo.com', 0x46, 'Scott Anderson', 21);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('vadimdovbysh', 'vcj0mk6xj3l7g1zj@gmail.gov', 0x4D, 'Kayla Edwards', 42);
INSERT INTO `ER-2`.Critic (UserName, Email, Sex, Name, age) VALUES ('yorktown_hawk', 'q1pwhxy@charter.net', 0x4D, 'Sandra Huffman', 24);