INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Cinematography', 2018, 5683, 1856101, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Cinematography', 2019, 190859, 6155172, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Cinematography', 2020, 5683, 8579674, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Costume Design', 2020, 244330, 3281548, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Directing', 2018, 868219, 5580390, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Directing', 2019, 190859, 6155172, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Film Editing', 2018, 809059, 5013056, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Film Editing', 2019, 653211, 1727824, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Music Written for Motion Pictures (Original Score)', 2018, 6035, 5580390, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Music Written for Motion Pictures (Original Score)', 2019, 3234869, 1825683, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Achievement in Sound Editing', 2020, 843219, 1950186, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Adapted Screenplay', 2020, 169806, 2584384, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Foreign Language Film of the Year', 2018, null, 5639354, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Foreign Language Film of the Year', 2019, null, 6155172, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Live Action Short Film', 2020, 1903582, 8163822, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Motion Picture of the Year', 2018, 868219, 5580390, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Motion Picture of the Year', 2019, null, 6966692, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Motion Picture of the Year', 2020, null, 6751668, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Leading Role', 2018, 198, 4555426, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Leading Role', 2019, 1727824, 1785339, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Leading Role', 2020, 1618, 7286456, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Supporting Role', 2018, 5377, 5027774, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Supporting Role', 2019, 991810, 6966692, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actor in a Supporting Role', 2020, 93, 7131622, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Leading Role', 2018, 531, 5027774, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Leading Role', 2019, 1469236, 5083738, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Leading Role', 2020, 250, 7549996, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Supporting Role', 2018, 5049, 5580036, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Supporting Role', 2019, 5093, 7125860, null);
INSERT INTO `ER-2`.Award (Name, Category, Year, Person_ID, Movie_ID, TV_Series_ID) VALUES ('Oscars', 'Best Performance by an Actress in a Supporting Role', 2020, 368, 7653254, null);